【em-standard-js】eslint 报错时，无法 git commit 成功
1msoft/em-standard-js pull request #8
Opened 2019-04-12 10:47 UTC by MeetTheBest

…s://www.tapd.cn/22105901/s/1008003 --story=1001349 --user=蒋芳江

2019-04-15 03:21 UTC, Rookie-Kang approved these changes

2019-04-15 05:07 UTC, 1msoft requested changes
1. 根目录已经有一个 .eslintrc.yml 配置，而且已经有airbnb的配置了（还包含一些自定义规则），需要结合来看，不是直接加一个文件
2. 根目录是不是加一个 .npmrc
3. package.json 里，版本号安装用精确版本号吧
4. 另外用了 prettier 之后， editorconfig 是否还有需要保留？

2019-04-16 10:43 UTC, MeetTheBest commented
> 1. 根目录已经有一个 .eslintrc.yml 配置，而且已经有airbnb的配置了（还包含一些自定义规则），需要结合来看，不是直接加一个文件
> 2. 根目录是不是加一个 .npmrc
> 3. package.json 里，版本号安装用精确版本号吧
> 4. 另外用了 prettier 之后， editorconfig 是否还有需要保留？

我们还是不要prettier哈, editorconfig的挺好用的, 因为我们没有装editorconfig这个依赖,所以我们的vscode里面需要对应的editorconfig的插件才可以生效

2019-04-16 10:55 UTC, Rookie-Kang approved these changes

2019-04-17 09:07 UTC, 1msoft approved these changes

2019-04-17 09:07 UTC, merged